### ISSUE TITLE
About the structure and conversion of AicvDataset dataset

### ISSUE THREAD

**Issue by windzu** [Tartisan/MMDet3d-CenterPoint#2]
Hello, first of all, thank you for your work on Tensorrt deployment based on mmdet3d, which saved me a lot of time (giving me more time " mess arround ")  At the same time, I noticed that the dataset you used is custom AicvDataset, and the relevant dataloader is implemented in the mmdetection3d project

Because that project cannot submit issus, so I am here to submit issus, please forgive me

Is it convenient for you to introduce the data structure of AicvDataset? In this way, I can convert my own data set to AicvDataset format, and then I can easily reuse your project 

Thanks

**Comment by Tartisan** [comment]
Sorry for replying so late, the format is inconvenient to disclose due to privacy reasons. You can organize your own data according to KITTI data format, or refer to the doc [customize_dataset.md](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/en/tutorials/customize_dataset.md) of mmdet3d
